language: csharp
mono: none
dotnet: 2.1
mono: latest

jobs:
  include:
    - stage: "Build"
      name: "Build nuget package"
      script:
        - dotnet build AberFitnessLayout -c Release
        # TODO publish package

notifications:
    slack: sem5640-2018:gxXCLVtsXyVq3214Oxq33ArB
